### ISSUE TITLE
Incompatible with node v4

### ISSUE THREAD

**Issue by laggingreflex** [buunguyen/mongoose-deep-populate#27]
So I just upgraded to node v4 (on Windows 8.1 x64) and it seems to have broken this module. It gives the following error:

    schema.plugin(deepPopulate)

    TypeError: Cannot read property 'prototype' of undefined
        at module.exports (C:\~\node_modules\mongoose-deep-populate\lib\plugin.js:6:21)
        at Schema.plugin (C:\~\node_modules\mongoose\lib\schema.js:796:3)

**Comment by laggingreflex** [comment]
Ahh actually my bad, I didn't pass it the mongoose object which it requires now in 1.x version.
