### ISSUE TITLE
Plugin was not installed

### ISSUE THREAD

**Issue by bhargavdath** [buunguyen/mongoose-deep-populate#30]
```javascript
Error: Plugin was not installed
    at Query.deepPopulate (/home/user/Desktop/project/node_modules/mongoose-deep-populate/lib/plugin.js:29:13)
    at /home/user/Desktop/project/app/controllers/resumes.server.controller.js:179:6
    at /home/user/Desktop/project/node_modules/async/lib/async.js:567:21
    at /home/user/Desktop/project/node_modules/async/lib/async.js:246:17
    at /home/user/Desktop/project/node_modules/async/lib/async.js:122:13
    at _each (/home/user/Desktop/project/node_modules/async/lib/async.js:46:13)
    at async.each (/home/user/Desktop/project/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/user/Desktop/project/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/user/Desktop/project/node_modules/async/lib/async.js:216:23)
    at _parallel (/home/user/Desktop/project/node_modules/async/lib/async.js:565:20)
    at Object.async.parallel (/home/user/Desktop/project/node_modules/async/lib/async.js:595:9)
    at exports.addCommentToResume (/home/user/Desktop/project/app/controllers/resumes.server.controller.js:158:8)
    at Layer.handle [as handle_request] (/home/user/Desktop/project/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/user/Desktop/project/node_modules/express/lib/router/route.js:100:13)
    at next (/home/user/Desktop/project/node_modules/express/lib/router/route.js:94:14)
    at Route.dispatch (/home/user/Desktop/project/node_modules/express/lib/router/route.js:81:3)
```

Here is the full code of model
```
var mongoose = require('mongoose'),
    extend = require('mongoose-schema-extend'),
	Schema = mongoose.Schema,
	deepPopulate = require('mongoose-deep-populate')(mongoose);

var PicsSchema = new Schema({
	userId: {
		type: mongoose.Schema.Types.ObjectId,
		ref: 'User'
	},
	picId: {
		type: mongoose.Schema.Types.ObjectId,
		ref: Pics'
	},
	comment: {
		type: String,
		trim: true,
		required: 'Comment field is mandatory'
	},
	createdAt: {
		type: Date,
		default: Date.now
	}
});

PicsSchema.plugin(deepPopulate);

mongoose.model('Pics', PicsSchema, 'pics');
```

**Comment by corey-mitchell** [comment]
@bhargavdath Can you tell me how you solved this issue?
