### ISSUE TITLE
Maximum call stack size exceeded?

### ISSUE THREAD

**Issue by alemonmk** [buunguyen/mongoose-deep-populate#36]
Hi, I encountered some really weird problem:
```
RangeError: Maximum call stack size exceeded
      at isFinite (native)
      at Buffer.write (buffer.js:559:14)
      at serializeObject (node_modules\mongoose\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:276:37)
      at serializeInto (node_modules\mongoose\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:551:17)
      at serializeObject (node_modules\mongoose\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:280:18)
      at serializeInto (node_modules\mongoose\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:705:17)
      at serializeObject (node_modules\mongoose\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:280:18)
      ...
```

Schema definitions:
https://github.com/alemonmk/bonappetit-nodejsserver/blob/develop/models/mongo_models.js

Access code:
https://github.com/alemonmk/bonappetit-nodejsserver/blob/develop/routes/user.js#L120

Problem still occurs even I shorten the path to only `cart.content`, and it doesn't matter whether `cart.content` has data or not.

Using koa@1, mongoose@4.3.5, mongoose-deep-populate@2.0.3.

What did I miss?

**Comment by buunguyen** [comment]
Please post fully working code or a failed test.

**Comment by alemonmk** [comment]
Okay, I changed the original post.

**Comment by buunguyen** [comment]
Please post a single piece of code that: 1. can be copied and pasted to my IDE, 2. can be executed immediately without change and 3. it throws the error in question. I don't have time to debug your app.

**Comment by alemonmk** [comment]
Fine...please have a look at this test: https://gist.github.com/alemonmk/a4289640798d31afe1eb

It seems that I was misled by `README->Perform population->On an instance of Post` as I don't know what the instance of `Post` is and use the retrieved document to do population.

But even I use the populate on `Query` way, the error in question is still there, I don't know where to look as the stack trace are truncated, and I'm unable to reproduce it out of my app :/

Forgot to mention I use node@5.4 with `--harmony` flag.

**Comment by alemonmk** [comment]
I'm sorry for bringing up a non-issue, I've confirmed that the problem is not about your plugin.
